<?php

/**
 * @file
 * Enforce Profile Field module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

function enforce_profile_field_allowed_values() {
  $values = [
    'key' => 'Lable',
    'test' => 'Test',
  ];

  return $values;
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * Perform alterations on Field API widget types to let the Enforce profile
 * field type re-use an existing widget.
 */
function enforce_profile_field_field_widget_info_alter(array &$info) {
  $info['options_select']['field_types'][] = 'enforce_profile_field';
}

/**
 * Implements hook_entity_view_alter().
 */
function enforce_profile_field_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  if (!($entity instanceof FieldableEntityInterface) || !$entity->hasField('enforce_profile_field')) {
    return;
  }

  $entity_type = $entity->getEntityTypeId();
}
